version: '3'

services:
  front:
    build: .
    container_name: front
    environment:
      - MVC_SERVER=192.168.10.15
      - MVC_DB=fantoche
      - MVC_USER=fantoche
      - MVC_TOKEN=QUl7YhWm
      - MVC_DEBUG=false
    command: php -S 0.0.0.0:9000
    volumes:
      - .:/var/www/html/
    restart: unless-stopped
    # ports:
    # - "9000:9000"
